import type { Metadata } from 'next'
import PageHero from '@/components/shared/PageHero'
import SectionHeading from '@/components/shared/SectionHeading'
import CopyButton from '@/components/shared/CopyButton'
import Reveal from '@/components/ui/Reveal'
import Icon from '@/components/shared/Icons'
import { site } from '@/data/site'

export const metadata: Metadata = {
  title: 'Brand Kit',
  description:
    'Official MLC logos, colors, typography, and messaging — for volunteers, partners, and press.',
}

// Assets generated by scripts/generate-brand-kit.mjs into public/brand/
const logoFiles = [
  {
    file: 'msc-logo-mark.svg',
    name: 'Primary mark',
    note: 'Default on light backgrounds',
    bg: 'bg-white',
  },
  {
    file: 'msc-logo-mark-white.svg',
    name: 'Reversed mark',
    note: 'On teal or dark photos',
    bg: 'bg-msc-teal',
  },
  {
    file: 'msc-logo-mark-color.svg',
    name: 'No-tile mark',
    note: 'When the tile feels heavy',
    bg: 'bg-msc-cream',
  },
  {
    file: 'msc-logo-mark-mono.svg',
    name: 'Mono mark',
    note: 'Single-color printing',
    bg: 'bg-white',
  },
]

const colors = [
  { hex: '#1A6B72', name: 'MLC Teal', use: 'Primary brand color', darkText: false },
  { hex: '#135459', name: 'Teal Dark', use: 'Hover states', darkText: false },
  { hex: '#E8F4F5', name: 'Teal Light', use: 'Tinted backgrounds', darkText: true },
  { hex: '#E8A020', name: 'MLC Amber', use: 'Buttons & CTAs only', darkText: true },
  { hex: '#FEF3D0', name: 'Amber Light', use: 'Highlight washes', darkText: true },
  { hex: '#E05C4B', name: 'MLC Coral', use: 'Errors & alerts only', darkText: false },
  { hex: '#F8F6F1', name: 'Cream', use: 'Warm section backgrounds', darkText: true },
  { hex: '#1C1C1E', name: 'Charcoal', use: 'Body text', darkText: false },
]

const boilerplates = [
  {
    label: 'One-liner',
    text: 'The Multilingual Support Collective (MLC) is a youth-led 501(c)(3) nonprofit bridging language gaps in healthcare, education, and community life.',
  },
  {
    label: 'Short paragraph',
    text: 'The Multilingual Support Collective (MLC) is a youth-led 501(c)(3) nonprofit that creates free multilingual resources, tutoring programs, and communication tools for families, students, and underserved communities. From bilingual healthcare phrase libraries to volunteer ESL tutoring, MLC works toward a world where language is never a barrier to health, education, or belonging. Everything MLC makes is free.',
  },
]

export default function BrandPage() {
  return (
    <>
      <PageHero
        eyebrow="Brand kit"
        title="One brand, many hands"
        description="Official MLC logos, colors, type, and messaging — everything volunteers, partners, and press need to represent us consistently. Download individual files below or grab the whole kit."
        actions={[
          { label: 'Download Full Kit (.zip)', href: '/brand/msc-brand-kit.zip' },
          { label: 'Brand Guidelines (PDF)', href: '/brand/msc-brand-guidelines.pdf', variant: 'secondary' },
        ]}
      />

      {/* ============ LOGOS ============ */}
      <section className="py-16 bg-white">
        <div className="container">
          <SectionHeading
            eyebrow="Logo"
            title="The mark"
            description="Two overlapping speech bubbles: a conversation, and a collective. SVGs scale to any size — use them for print and web; PNGs are for slides and docs."
          />
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-5 max-w-4xl mx-auto mb-8">
            {logoFiles.map((logo, i) => (
              <Reveal key={logo.file} delay={i * 0.07}>
                <div className="h-full rounded-2xl border border-gray-100 shadow-sm overflow-hidden flex flex-col">
                  <div className={`${logo.bg} flex items-center justify-center py-9`}>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src={`/brand/${logo.file}`} alt={logo.name} className="w-16 h-16" />
                  </div>
                  <div className="p-4 bg-white flex-1 flex flex-col">
                    <p className="text-sm font-bold text-msc-charcoal">{logo.name}</p>
                    <p className="text-xs text-gray-500 mb-3 flex-1">{logo.note}</p>
                    <a
                      href={`/brand/${logo.file}`}
                      download
                      className="text-xs font-semibold text-msc-teal hover:underline"
                    >
                      Download SVG ↓
                    </a>
                  </div>
                </div>
              </Reveal>
            ))}
          </div>
          <Reveal className="text-center">
            <p className="text-sm text-gray-500">
              Also in the kit:{' '}
              <a href="/brand/msc-logo-horizontal.png" download className="text-msc-teal font-semibold hover:underline">
                horizontal lockup
              </a>
              {' · '}
              <a href="/brand/msc-logo-horizontal-white.png" download className="text-msc-teal font-semibold hover:underline">
                white lockup
              </a>
              {' · '}
              <a href="/brand/msc-logo-mark-512.png" download className="text-msc-teal font-semibold hover:underline">
                512px PNG mark
              </a>
            </p>
          </Reveal>
        </div>
      </section>

      {/* ============ COLORS ============ */}
      <section className="py-16 bg-msc-cream">
        <div className="container">
          <SectionHeading
            eyebrow="Color"
            title="Teal leads. Amber acts."
            description="Click any hex code to copy it. Amber is for buttons and CTAs only — never text on white. Coral is reserved for errors."
          />
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto">
            {colors.map((c, i) => (
              <Reveal key={c.hex} delay={i * 0.05}>
                <div className="rounded-2xl overflow-hidden border border-gray-100 shadow-sm bg-white">
                  <div
                    className="h-20 flex items-end justify-between p-3"
                    style={{ backgroundColor: c.hex }}
                  >
                    <span
                      className={`text-[11px] font-bold ${c.darkText ? 'text-msc-charcoal/80' : 'text-white/90'}`}
                    >
                      {c.hex}
                    </span>
                    <CopyButton text={c.hex} />
                  </div>
                  <div className="p-3.5">
                    <p className="text-sm font-bold text-msc-charcoal">{c.name}</p>
                    <p className="text-xs text-gray-500">{c.use}</p>
                  </div>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* ============ TYPOGRAPHY ============ */}
      <section className="py-16 bg-white">
        <div className="container">
          <SectionHeading
            eyebrow="Typography"
            title="One voice: Open Sauce One."
            description="A single, friendly geometric sans carries everything — headings, body, and UI. Where it's unavailable (Docs, Slides), substitute Arial."
          />
          <div className="grid md:grid-cols-2 gap-6 max-w-4xl mx-auto">
            <Reveal>
              <div className="h-full rounded-2xl border border-gray-100 shadow-sm p-8">
                <p className="text-xs font-bold uppercase tracking-widest text-msc-amber mb-4">
                  Display & headings — Open Sauce One
                </p>
                <p className="text-3xl font-bold text-msc-charcoal leading-snug mb-4">
                  Language is the front door to everything
                </p>
                <p className="text-sm text-gray-600 leading-relaxed">
                  Bold weights (600–700) for headlines, pull quotes, and section titles. Set tight and
                  large for the confident, editorial feel. Never below 13px.
                </p>
              </div>
            </Reveal>
            <Reveal delay={0.1}>
              <div className="h-full rounded-2xl border border-gray-100 shadow-sm p-8">
                <p className="text-xs font-bold uppercase tracking-widest text-msc-amber mb-4">
                  Body & UI — Open Sauce One
                </p>
                <p className="text-base text-msc-charcoal leading-relaxed mb-4">
                  Body copy, buttons, forms, navigation, and captions use the same family at 400–600 —
                  one typeface keeps the voice consistent and the loading light.
                </p>
                <p className="text-sm text-gray-600 leading-relaxed">
                  Eyebrow labels: bold, all caps, wide tracking, teal. Editorial micro-labels use a
                  monospace stack for a technical accent.
                </p>
              </div>
            </Reveal>
          </div>
        </div>
      </section>

      {/* ============ MESSAGING ============ */}
      <section className="py-16 bg-msc-cream">
        <div className="container">
          <SectionHeading
            eyebrow="Messaging"
            title="Copy-paste ready"
            description="Use these verbatim in grant applications, press mentions, event programs, and partner sites."
          />
          <div className="max-w-3xl mx-auto space-y-5">
            <Reveal>
              <div className="rounded-2xl bg-white border border-gray-100 shadow-sm p-7 text-center">
                <p className="text-xs font-bold uppercase tracking-widest text-msc-teal mb-2">Tagline</p>
                <p className="text-3xl font-bold text-msc-teal mb-4">Language is access.</p>
                <CopyButton text="Language is access." label="Copy tagline" />
              </div>
            </Reveal>
            {boilerplates.map((b, i) => (
              <Reveal key={b.label} delay={0.05 + i * 0.05}>
                <div className="rounded-2xl bg-white border border-gray-100 shadow-sm p-7">
                  <div className="flex items-center justify-between mb-3">
                    <p className="text-xs font-bold uppercase tracking-widest text-msc-teal">{b.label}</p>
                    <CopyButton text={b.text} />
                  </div>
                  <p className="text-sm text-gray-600 leading-relaxed">{b.text}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* ============ QUESTIONS ============ */}
      <section className="py-16 bg-white">
        <div className="container text-center">
          <Reveal>
            <span className="w-12 h-12 rounded-xl bg-msc-teal-light text-msc-teal flex items-center justify-center mx-auto mb-4">
              <Icon name="chat" className="w-6 h-6" />
            </span>
            <h2 className="text-2xl font-bold text-msc-charcoal mb-2">Questions about using the brand?</h2>
            <p className="text-gray-600 mb-5">
              Making something for MLC and not sure it fits? Send it over — we're fast.
            </p>
            <a href={`mailto:${site.email}?subject=${encodeURIComponent('[Brand] Question about brand usage')}`} className="btn-secondary">
              Email {site.email}
            </a>
          </Reveal>
        </div>
      </section>
    </>
  )
}
